services:
  mysql:
    image: mysql:8.0
    container_name: service-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: service
      MYSQL_USER: service
      MYSQL_PASSWORD: service
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --lower_case_table_names=1
