### 할일 생성 API
POST {{endpoint}}/api/todos
Content-Type: application/json

{
  "title": "title",
  "content": "content"
}

> {%
    client.global.set("created_todo_location", response.headers.valueOf("location"))
    client.log(client.global.get("created_todo_location"))
%}


### 할일 조회 API
GET {{endpoint}}{{created_todo_location}}


### 할일 목록 조회 API
GET {{endpoint}}/api/todos
