name: ec2 deploy with aws code deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github repository checkout
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle 빌드
        run: ./gradlew clean build

      - name: Archive 파일명 가공
        run: mv ./build/libs/*SNAPSHOT.jar ./app.jar

      - name: ENV 파일 생성
        run: echo "${{ secrets.ENV_PROPERTIES }}" > ./.env

      - name: S3 파일 전송을 위한 압축
        run: tar -czvf $GITHUB_SHA.tar.gz app.jar appspec.yml scripts .env

      - name: Github Actions에게 부여한 IAM User을 이용하여 AWS Resources에 접근하기 위한 Credential 설정
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: AWS Cli를 이용하여 S3에 압축 파일 전송
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.tar.gz s3://todo-app/$GITHUB_SHA.tar.gz

      - name: CodeDeploy를 이용한 EC2 배포 프로세스 시작
        run: aws deploy create-deployment # 신규 배포 생성
          --application-name service-app # 배포 대상 Application 지정
          --deployment-config-name CodeDeployDefault.AllAtOnce # 배포 방식 지정: AllAtOnce 모든 인스턴스를 한번에 배포
          --deployment-group-name # 배포 그룹 선택
          --s3-location bucket=service-app-artifact,bundleType=tgz,key=$GITHUB_SHA.tar.gz # 배포 파일이 저장된 S3 bucket 이름과, 확장자, 파일명 지정
